version: "3"

volumes:
  alias_bindfs_mapped_data:
    driver: lebokus/bindfs:latest
    labels:
      - com.docker-alias=true
    driver_opts:
      sourcePath: "${PWD}"
      map: "${LOCAL_UID}/0:@${LOCAL_UID}/@0"

services:
  node:
    image: node:4
    volumes:
     - alias_bindfs_mapped_data:/docker_alias_work_dir
    working_dir: /docker_alias_work_dir
    labels:
     - com.docker-alias.name=npm

  composer:
    image: composer
    volumes:
     - alias_bindfs_mapped_data:/docker_alias_work_dir
     - $SSH_AUTH_SOCK:/ssh-auth.sock
     - /var/cache/composer:/var/cache
    working_dir: /docker_alias_work_dir
    environment:
     - SSH_AUTH_SOCK=/ssh-auth.sock
     - COMPOSER_CACHE_DIR=/var/cache
    labels:
     - com.docker-alias.name=composer
