version: "3"

volumes:
  alias_bindfs_mapped_data:
    driver: lebokus/bindfs:latest
    labels:
      - com.docker-alias=true
    driver_opts:
      sourcePath: "${PWD}"
      map: "${LOCAL_UID}/0:@${LOCAL_UID}/@0"

services:
  node:
    image: node:4
    volumes:
     - alias_bindfs_mapped_data:/var/www/html
    working_dir: /var/www/html
    labels:
     - com.docker-alias.name=npm

  composer:
    image: composer
    volumes:
     - alias_bindfs_mapped_data:/var/www/html
     - $SSH_AUTH_SOCK:/ssh-auth.sock
     - /var/cache/composer:/var/cache
    working_dir: /var/www/html
    environment:
     - SSH_AUTH_SOCK=/ssh-auth.sock
     - COMPOSER_CACHE_DIR=/var/cache
    labels:
     - com.docker-alias.name=composer

  #x11 passthrough   
  rider:
    build:
      context: .
      dockerfile: .deployment/docker/alias/rider/Dockerfile
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - $HOME:$HOME
    labels:
      - com.docker-alias.name=rider
      - com.docker-alias.command=/usr/local/bin/userswitch.sh /opt/rider/bin/rider.sh
      # userswitch.sh
      # set -e
      # useradd -u $LOCAL_UID $USER
      # su $USER -c "$@"
      - com.docker-alias.detach=true
      - com.docker-alias.silent=true
      - com.docker-alias.preExecutionCommand=xhost +local:root;
    environment:
      - DISPLAY
      - LOCAL_UID
      - USER
