#!/usr/bin/env bash

set -e

USER_BIN_DIR="$HOME/.local/bin"
USER_SYSTEMD_UNIT_DIR="$HOME/.config/systemd/user"
DOCKER_ALIAS_ROOT="$HOME/.local/docker-alias"
DOCKER_ALIAS_BINARY_ROOT="$DOCKER_ALIAS_ROOT/bin"
DOCKER_ALIAS_CONFIG_ROOT="$HOME/.config/docker-alias"
DOCKER_ALIAS_CLI_BINARY="$DOCKER_ALIAS_ROOT/cli/cli"
DOCKER_ALIAS_CLI_SYMLINK="$USER_BIN_DIR/docker-alias"

DOCKER_ALIAS_DAEMON_SYSTEMD_FILE="docker-alias.service"
DOCKER_ALIAS_DAEMON_SYSTEMD_UNIT_PATH="$DOCKER_ALIAS_ROOT/daemon/$DOCKER_ALIAS_DAEMON_SYSTEMD_FILE"
DOCKER_ALIAS_DAEMON_SYSTEMD_SYMLINK="$USER_SYSTEMD_UNIT_DIR/$DOCKER_ALIAS_DAEMON_SYSTEMD_FILE"

BASH_PROFILE="$HOME/.profile"
DOCKER_ALIAS_PATH="PATH=\$HOME/.local/docker-alias/bin:\$PATH"

if [ ! -d "$USER_BIN_DIR" ]; then mkdir "$USER_BIN_DIR"; fi
if [ ! -d "$USER_SYSTEMD_UNIT_DIR" ]; then mkdir -p "$USER_SYSTEMD_UNIT_DIR"; fi
if [ ! -d "$DOCKER_ALIAS_ROOT" ]; then mkdir "$DOCKER_ALIAS_ROOT"; fi
if [ ! -d "$DOCKER_ALIAS_CONFIG_ROOT" ]; then mkdir "$DOCKER_ALIAS_CONFIG_ROOT"; fi
if [ ! -d "$DOCKER_ALIAS_BINARY_ROOT" ]; then mkdir "$DOCKER_ALIAS_BINARY_ROOT"; fi
if [ -f "$DOCKER_ALIAS_CLI_SYMLINK" ]; then rm "$DOCKER_ALIAS_CLI_SYMLINK"; fi
if [ -f "$DOCKER_ALIAS_DAEMON_SYSTEMD_SYMLINK" ]; then rm "$DOCKER_ALIAS_DAEMON_SYSTEMD_SYMLINK"; fi

systemctl --user stop "$DOCKER_ALIAS_DAEMON_SYSTEMD_FILE" || true
cp -r . "$DOCKER_ALIAS_ROOT"
chmod +x "$DOCKER_ALIAS_CLI_BINARY"
ln -s "$DOCKER_ALIAS_CLI_BINARY" "$DOCKER_ALIAS_CLI_SYMLINK"
ln -s "$DOCKER_ALIAS_DAEMON_SYSTEMD_UNIT_PATH" "$DOCKER_ALIAS_DAEMON_SYSTEMD_SYMLINK"
systemctl --user daemon-reload
systemctl --user enable "$DOCKER_ALIAS_DAEMON_SYSTEMD_FILE"
systemctl --user start "$DOCKER_ALIAS_DAEMON_SYSTEMD_FILE"

if ! grep -q "$DOCKER_ALIAS_PATH" "$BASH_PROFILE"; then
  echo "$DOCKER_ALIAS_PATH" >> "$BASH_PROFILE"
fi
source "$BASH_PROFILE"
